name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload latest website data to S3 bucket
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credential
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::472725201054:role/github-oidc-Role-SE7vsFZCRq0A
        aws-region: us-east-1
    - name: Copy website data to S3 bucket
      run: |
        aws s3 sync . s3://www.qpalms.com/ --exclude ".git/*" --exclude ".github/*" --exclude ".gitignore" --exclude "temp/*"
